# Generated by Django 4.2.6 on 2023-10-27 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('ward_number', models.IntegerField(default=3)),
            ],
        ),


        migrations.RemoveField(
            model_name='vct',
            name='classroom',
        ),
        migrations.RenameModel(
            old_name='goat',
            new_name='VCT',
        ),
        migrations.AddField(
            model_name='vct',
            name='VCTroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Folder.personaldata'),
        ),
    ]
